home:
  path: /
  controller: App\Controller\HomeController::home
  methods: GET

app_portfolio:
  path: /portfolio
  controller: App\Controller\PortfolioController::portfolio
  methods: GET

app_project_show:
  path: /portfolio/{project}
  controller: App\Controller\PortfolioController::show
  methods: GET

app_contact:
  path: /contact
  controller: App\Controller\ContactController::contact
  methods: GET|POST

app_login:
  path: /login
  controller: App\Controller\SecurityController::login
  methods: GET|POST

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout
  methods: GET

app_admin_dashboard:
  path: /api-admin/dashboard
  controller: App\Controller\AdminController::dashboard
  methods: GET

app_admin_register:
  path: /api-admin/register
  controller: App\Controller\UserController::register
  methods: GET|POST
